# Generated by Django 4.0.3 on 2022-03-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_job_user'),
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
