# Generated by Django 4.0.3 on 2022-03-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('minimum_wage', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('landmark', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.category')),
            ],
        ),
    ]
