# Generated by Django 4.0.3 on 2022-03-16 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_reviewrating_job_alter_reviewrating_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
